//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.BorrowAndReturn = new HashSet<BorrowAndReturn>();
        }
    
        public int Id { get; set; }
        public string BookCode { get; set; }
        public Nullable<int> IdTypeOfBook { get; set; }
        public Nullable<bool> Status { get; set; }
        public string CoverImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowAndReturn> BorrowAndReturn { get; set; }
        public virtual TypeOfBook TypeOfBook { get; set; }
    }
}
