//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowAndReturn
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> BorrowDay { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdBook { get; set; }
        public Nullable<System.DateTime> ReturnDay { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
